### PR TITLE
Feature/live reload

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@donnapep @stulees please review.

You can check the stage version here:

http://s3.amazonaws.com/widget-preview-dl-test/0.3.0/widget-preview-osx64.zip

In the settings there a new section where you can set the files the application should watch for live reload. Please let me know if you find any issue.

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi I couldn't get this to work for me when setting some dist/ files for the app to watch. Can you give me an example change (using rss widget for example) that I could do and see reflected in the browser?

**Comment by stulees** [comment]
@rodrigopavezi Ah, I see now that to make this work we can't point the settings and widget HTML files to the dist/ ones, they need to be the src/ ones. Do I have this right?

**Comment by rodrigopavezi** [comment]
@stulees I noticed that if the folder where the file that is being watched get deleted the watcher cannot find the file anymore. So we can try to change the widgets to not delete the folders under dist only the files. Cheers

**Comment by stulees** [comment]
@rodrigopavezi :+1:  Okay thanks for clarifying that. I don't think we'll want to commit only deleting files from a gulp clean, but we can always modify the gulp task locally for ourselves to make use of this live reload feature. Cheers

**Comment by donnapep** [comment]
@rodrigopavezi Live reload is working well for me. Thx! :+1:

**Pull request merged**
